<a href="https://colab.research.google.com/github/therealhaseeb/Numpy-Tutorial/blob/main/Linear_Algebra_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Create an array from an iterable
Such as
*   list
*   tuple
*   range iterator

Notice that not all iterables can be used to create a numpy array, such as set and dict



In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [4]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Create an array with specified data type


In [6]:
arr = np.array([[1,2,3], [4,5,6]], dtype='int32')
print(arr)
print('Data Type: ' + str(arr.dtype))

[[1 2 3]
 [4 5 6]]
Data Type: int32


In [7]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


inspect general information of an array


In [14]:
arr1 = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

print(arr1.shape)

(2, 3)


In [15]:
print(arr.dtype)


int64


In [16]:
print(len(arr))


2


In [17]:
print(arr.ndim)


2


In [18]:
print(arr.size)


6


In [25]:
arr = np.random.rand(5,5)
arr

array([[0.29371405, 0.63097612, 0.09210494, 0.43370117, 0.43086276],
       [0.4936851 , 0.42583029, 0.31226122, 0.42635131, 0.89338916],
       [0.94416002, 0.50183668, 0.62395295, 0.1156184 , 0.31728548],
       [0.41482621, 0.86630916, 0.25045537, 0.48303426, 0.98555979],
       [0.51948512, 0.61289453, 0.12062867, 0.8263408 , 0.60306013]])

element-wise operations


In [27]:
print(arr + 10)

[[10.29371405 10.63097612 10.09210494 10.43370117 10.43086276]
 [10.4936851  10.42583029 10.31226122 10.42635131 10.89338916]
 [10.94416002 10.50183668 10.62395295 10.1156184  10.31728548]
 [10.41482621 10.86630916 10.25045537 10.48303426 10.98555979]
 [10.51948512 10.61289453 10.12062867 10.8263408  10.60306013]]


In [28]:
print(arr - 10)

[[-9.70628595 -9.36902388 -9.90789506 -9.56629883 -9.56913724]
 [-9.5063149  -9.57416971 -9.68773878 -9.57364869 -9.10661084]
 [-9.05583998 -9.49816332 -9.37604705 -9.8843816  -9.68271452]
 [-9.58517379 -9.13369084 -9.74954463 -9.51696574 -9.01444021]
 [-9.48051488 -9.38710547 -9.87937133 -9.1736592  -9.39693987]]


In [29]:
print(arr * 10)

[[2.93714046 6.30976124 0.9210494  4.33701173 4.30862763]
 [4.93685098 4.2583029  3.12261223 4.26351307 8.93389163]
 [9.44160018 5.01836676 6.23952952 1.15618395 3.17285482]
 [4.14826212 8.66309158 2.50455365 4.83034264 9.85559786]
 [5.19485119 6.12894526 1.20628666 8.26340801 6.03060128]]


In [30]:
print(arr / 10)

[[0.0293714  0.06309761 0.00921049 0.04337012 0.04308628]
 [0.04936851 0.04258303 0.03122612 0.04263513 0.08933892]
 [0.094416   0.05018367 0.0623953  0.01156184 0.03172855]
 [0.04148262 0.08663092 0.02504554 0.04830343 0.09855598]
 [0.05194851 0.06128945 0.01206287 0.08263408 0.06030601]]


In [31]:
print(np.log(arr))


[[-1.22514862 -0.46048726 -2.3848267  -0.83539952 -0.84196565]
 [-0.70585742 -0.85371439 -1.16391519 -0.85249161 -0.112733  ]
 [-0.05745962 -0.68948056 -0.47168031 -2.15746021 -1.14795334]
 [-0.87989561 -0.14351344 -1.38447456 -0.72766769 -0.01454549]
 [-0.65491711 -0.48956242 -2.11503833 -0.190748   -0.50573837]]


In [32]:
print(np.exp(arr))


[[1.34140027 1.87944425 1.09647988 1.54295772 1.53858439]
 [1.63834256 1.53086095 1.36651161 1.53165876 2.4433967 ]
 [2.57065317 1.65175222 1.86629084 1.12256741 1.3733946 ]
 [1.51410758 2.37811738 1.28461025 1.62098545 2.6793113 ]
 [1.68116183 1.84576629 1.12820589 2.28494236 1.82770326]]


In [33]:
print(np.sqrt(arr))


[[0.54195392 0.79434006 0.30348796 0.65855992 0.65640137]
 [0.70262728 0.65255673 0.55880338 0.65295582 0.94519266]
 [0.97167897 0.70840432 0.78990693 0.34002705 0.563281  ]
 [0.64407004 0.9307573  0.50045516 0.69500666 0.99275364]
 [0.72075316 0.7828758  0.34731638 0.90903289 0.77656946]]


In [34]:
print(np.sin(arr))


[[0.28950921 0.58993321 0.09197477 0.42023218 0.41765487]
 [0.47387417 0.41307707 0.30721129 0.4135515  0.77920046]
 [0.81000463 0.48103656 0.58424783 0.11536098 0.31198869]
 [0.40303089 0.76194378 0.24784514 0.46446842 0.83358144]
 [0.49643325 0.57523755 0.12033633 0.73545693 0.56716546]]


In [35]:
print(np.cos(arr))


[[0.95717523 0.80745205 0.99576134 0.90741662 0.90860575]
 [0.88059257 0.91069607 0.95164133 0.91048073 0.62677479]
 [0.58642347 0.87670053 0.8115753  0.99332364 0.95008582]
 [0.91518638 0.64764317 0.96879966 0.88558968 0.55239657]
 [0.8680749  0.81798641 0.99273318 0.67757147 0.82360387]]


In [36]:
arr = np.random.rand(10)
arr

array([0.54506801, 0.34276383, 0.30412079, 0.41702221, 0.68130077,
       0.87545684, 0.51042234, 0.66931378, 0.58593655, 0.6249035 ])

In [37]:
print(np.mean(arr))


0.5556308622978727


In [38]:
print(np.median(arr))


0.565502279514339


In [39]:
print(np.std(arr))


0.16329726065678934


In [40]:
arr = np.array(range(100)).reshape((10,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [41]:
print(arr[5][5])
# or more concisely
print(arr[5,5])


55
55


In [42]:
print(arr[1:3, 4:6])


[[14 15]
 [24 25]]


In [44]:
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [43]:
print(np.where(arr>5, -1, 10))


[[10 10 10 10 10 10 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]


In [51]:
arr = np.random.rand(3,5)
arr

array([[0.93193215, 0.58217546, 0.20609573, 0.71775756, 0.37898585],
       [0.66838395, 0.02931972, 0.63590036, 0.03219793, 0.74478066],
       [0.472913  , 0.12175436, 0.54263593, 0.06677444, 0.65336487]])

In [52]:
print(arr.T)


[[0.93193215 0.66838395 0.472913  ]
 [0.58217546 0.02931972 0.12175436]
 [0.20609573 0.63590036 0.54263593]
 [0.71775756 0.03219793 0.06677444]
 [0.37898585 0.74478066 0.65336487]]


In [55]:
arr = np.random.rand(6,9)
arr

array([[0.86545985, 0.02524236, 0.26690581, 0.5020711 , 0.06744864,
        0.99303326, 0.2364624 , 0.37429218, 0.21401191],
       [0.10544587, 0.23247979, 0.30061014, 0.63444227, 0.28123478,
        0.36227676, 0.00594284, 0.36571913, 0.53388598],
       [0.16201584, 0.59743311, 0.29315247, 0.63205049, 0.02619661,
        0.88759346, 0.01611863, 0.12695803, 0.77716246],
       [0.04589523, 0.71099869, 0.97104614, 0.87168293, 0.71016165,
        0.95850974, 0.42981334, 0.87287891, 0.35595767],
       [0.92976365, 0.14877766, 0.94002901, 0.8327162 , 0.84605484,
        0.12392301, 0.5964869 , 0.01639248, 0.72118437],
       [0.00773751, 0.08482228, 0.22549841, 0.87512453, 0.36357632,
        0.53995994, 0.56810321, 0.22546336, 0.57214677]])

In [57]:
print(arr.reshape((9,6)))


[[0.86545985 0.02524236 0.26690581 0.5020711  0.06744864 0.99303326]
 [0.2364624  0.37429218 0.21401191 0.10544587 0.23247979 0.30061014]
 [0.63444227 0.28123478 0.36227676 0.00594284 0.36571913 0.53388598]
 [0.16201584 0.59743311 0.29315247 0.63205049 0.02619661 0.88759346]
 [0.01611863 0.12695803 0.77716246 0.04589523 0.71099869 0.97104614]
 [0.87168293 0.71016165 0.95850974 0.42981334 0.87287891 0.35595767]
 [0.92976365 0.14877766 0.94002901 0.8327162  0.84605484 0.12392301]
 [0.5964869  0.01639248 0.72118437 0.00773751 0.08482228 0.22549841]
 [0.87512453 0.36357632 0.53995994 0.56810321 0.22546336 0.57214677]]


In [58]:
arr.flatten()


array([0.86545985, 0.02524236, 0.26690581, 0.5020711 , 0.06744864,
       0.99303326, 0.2364624 , 0.37429218, 0.21401191, 0.10544587,
       0.23247979, 0.30061014, 0.63444227, 0.28123478, 0.36227676,
       0.00594284, 0.36571913, 0.53388598, 0.16201584, 0.59743311,
       0.29315247, 0.63205049, 0.02619661, 0.88759346, 0.01611863,
       0.12695803, 0.77716246, 0.04589523, 0.71099869, 0.97104614,
       0.87168293, 0.71016165, 0.95850974, 0.42981334, 0.87287891,
       0.35595767, 0.92976365, 0.14877766, 0.94002901, 0.8327162 ,
       0.84605484, 0.12392301, 0.5964869 , 0.01639248, 0.72118437,
       0.00773751, 0.08482228, 0.22549841, 0.87512453, 0.36357632,
       0.53995994, 0.56810321, 0.22546336, 0.57214677])

In [59]:
arr = np.array([1,2,3])


In [60]:
arr1 = np.append(arr, 4)    
print(arr1)


[1 2 3 4]


In [61]:
arr2 = np.append(arr, [4,5,6])    
print(arr2)


[1 2 3 4 5 6]


In [64]:
arr4 = np.delete(arr2, 0)    
arr4

array([2, 3, 4, 5, 6])

In [68]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])


In [69]:
print(arr1)
print(arr2)

[[1 2 3 4]
 [1 2 3 4]]
[[5 6 7 8]
 [5 6 7 8]]


In [70]:
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)


[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [71]:
cat1 = np.concatenate((arr1, arr2), axis=1)    
print(cat1)


[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
